# Generated by Django 4.1.1 on 2022-10-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_ingredient_recipe_tag_shoppingcart_recipe_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название тэга', max_length=200, verbose_name='Название тэга'),
        ),
    ]
