# Generated by Django 4.1.1 on 2022-10-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_ingredient_ingredientamount_recipe_tag_shoppingcart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
    ]
