# Generated by Django 4.1.1 on 2022-10-12 19:02

from django.db import migrations, models
import product_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_ingredientamount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[product_app.validators.slug_validator], verbose_name='Метка URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[product_app.validators.username_validator], verbose_name='Имя пользователя'),
        ),
    ]
