# Generated by Django 4.1.1 on 2022-10-13 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_shoppingcart_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингридиентов 1'), django.core.validators.MaxValueValidator(10000, message='Максимальное количество ингридиентов 10000')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления 1 минута'), django.core.validators.MaxValueValidator(10000, message='Максимальное количество ингридиентов 10000')], verbose_name='Время приготовления'),
        ),
    ]
